# Generated by Django 5.0 on 2023-12-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthsat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_un_registery', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('orbit_class', models.CharField(choices=[('LEO', 'Low Earth Orbit'), ('MEO', 'Medium Earth Orbit'), ('GEO', 'Geostationary'), ('ELL', 'Elliptical')], max_length=255)),
                ('perigee_km', models.IntegerField()),
                ('apogee_km', models.IntegerField()),
                ('inclination_deg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_minutes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('launch_mass_kg', models.IntegerField()),
                ('launch_date', models.DateField()),
                ('expected_lifetime_yrs', models.IntegerField()),
                ('launch_site', models.CharField(max_length=255)),
                ('launch_vehicle', models.CharField(max_length=255)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='earthsat.operator')),
            ],
        ),
    ]
