# Generated by Django 5.0 on 2023-12-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthsat', '0002_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='expected_lifetime_yrs',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
