# Generated by Django 5.0 on 2023-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthsat', '0004_rename_purpose_satellite_purpose1_satellite_purpose2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='apogee_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='expected_lifetime_yrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='inclination_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_mass_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='perigee_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='period_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
